@echo off

SET CHOOSEVC=

REM SET CHOOSEVC=VS110

WHERE /q gmake.exe
IF ERRORLEVEL 1 (
ECHO Couldn't find gmake.exe. Please install.
GOTO:EOF
)

WHERE /q cl.exe
IF NOT ERRORLEVEL 1 (
GOTO :DOGMAKE
)

SETLOCAL ENABLEEXTENSIONS
SETLOCAL ENABLEDELAYEDEXPANSION

SET VCARG=VS150COMNTOOLS& CALL :CHECKVC
SET VCARG=VS140COMNTOOLS& CALL :CHECKVC
SET VCARG=VS130COMNTOOLS& CALL :CHECKVC
SET VCARG=VS120COMNTOOLS& CALL :CHECKVC
SET VCARG=VS110COMNTOOLS& CALL :CHECKVC

SET VCARG=
FOR %%X IN (!VCLIST!) DO (
   IF "%%X"=="!CHOOSEVC!COMNTOOLS" SET VCARG=%%X
)

IF "!VCARG!"=="" (
  FOR %%X IN (!VCLIST!) DO (
     IF "!VCARG!"=="" SET VCARG=%%X
  )
)

SET VCHOME=!%VCARG%!

CALL "!VCHOME!..\..\vc\bin\vcvars32.bat"

GOTO:DOGMAKE

:CHECKVC
IF DEFINED !VCARG! (
   IF NOT "!VCLIST!"=="" SET VCLIST=!VCLIST!,
   SET VCLIST=!VCLIST!!VCARG!
)
GOTO:EOF

:DOGMAKE
gmake %*